### ISSUE TITLE
[Request]: (Ventoy) Migrate to machine-wide/all-users install

### ISSUE THREAD

**Issue by teknowledgist** [asheroto/ChocolateyPackages#10]
### Describe the feature or improvement you're requesting

I see that you have put a lot of care into making the Ventoy package.  Thank you for your work. 

That said, Chocolatey is "a machine level package manager", and is intended to install "all-user" applications (into `$env:ProgramFiles`) or portable apps (into `%ChocolateyInstall%/lib`).  It is not a requirement of packages, in part because not all applications can work that way (e.g. GitHub Desktop), but [it is implied in the documentation](https://docs.chocolatey.org/en-us/faqs#what-distinction-does-chocolatey-make-between-an-installable-and-a-portable-application).  As a zip package, Ventoy could easily be placed in a location that is accessible to all users of the machine, and placing it only in the installing (admin) user's profile creates issues like:

* other Admin users can't see the application, but Chocolatey says it is installed.
* If a second admin user upgrades Ventoy, the first admin user must `--force` an upgrade again to get the latest version for themseleves because Chocolatey believes it is already upgraded.
* Unprivileged users can't access the application at all even if they know admin credentials for per-application elevation (as is recommended, industry standard).

Please consider changing the unzip location for Ventoy to the Chocolatey-standard within the package directory.  i.e. `%ChocolateyInstall%/lib/ventoy`.  

Thanks!

**Comment by asheroto** [comment]
Ahh good point. I inherited the package from someone and improved upon its code. I will change this later.

**Comment by asheroto** [comment]
@teknowledgist how do you think I should handle existing installed program?

Should I:
- Remove the items in the AppData folder?
- Ignore them

**Comment by asheroto** [comment]
https://github.com/asheroto/ChocolateyPackages/blob/15159ea98a01b0ebf0f6ff0634ad5720fe2bc544/ventoy/tools/chocolateyinstall.ps1#L15-L22

**Comment by asheroto** [comment]
The other problem I'm concerned about...

With iVentoy, it has folders/files that may need to continue to reside there, such as ISO files. So I guess I could just move the directories instead? That might be safer... although then I worry about permission issues.

Would love your feedback on this! Thanks!

**Comment by teknowledgist** [comment]
> removing the LocalAppData/ventoy folder.

The only possible problem I can imagine is if the upgrading user is not the original installing user (admin or not).  Then the installing user will have two start menu icons and two desktop icons (one each within their profile and one for all users) and access to two different versions of Ventoy.  

That is assuming you are planning on fixing the shortcut locations.  (You are going to do that, right?  😉 )

**Comment by teknowledgist** [comment]
I don't know much about iVentoy, but assuming it also doesn't have an installer, then I would suspect that all paths that it references are relative by default.  That means you should be able to move anything to the new install location.  

If the ISO directory is intended for users to drop things (ISOs) into, only Admins are going to be able to do that.  I don't see that as a problem though since the software probably required elevated rights to run anyway.  IOW, it can only be run by admins anyway.

**Comment by asheroto** [comment]
> > removing the LocalAppData/ventoy folder.
> 
> The only possible problem I can imagine is if the upgrading user is not the original installing user (admin or not). Then the installing user will have two start menu icons and two desktop icons (one each within their profile and one for all users) and access to two different versions of Ventoy.
> 
> That is assuming you are planning on fixing the shortcut locations. (You are going to do that, right? 😉 )

ugh, right. Well the issue is that the shortcuts are for the current user, which means it would indeed break the shortcuts. I'd almost have to scan each user's start menu and desktop folder for the same shortcuts to fix.

> IOW, it can only be run by admins anyway.

Right, so iVentoy may be need to ran by admins anyway since it creates a service and requires admin privileges. So I may be able to leave that alone.

--

What about creating an `-AllUsers` install to give users the option? It's either that, or deal with possible shortcut issues.

**Comment by teknowledgist** [comment]
In the vast majority of cases, the user who upgrades to the next (fixed) version will be the same user that installed it in the first place, and you can simply deal with the shortcuts the current script placed in their profile.  I wouldn't bother trying to look through all the user profiles for Ventoy shortcuts.  

If you put new shortcuts (to the new location) on the desktop and in the start menu, the rare, second admin who installed/upgraded Ventoy in the past will have two shortcuts in their profile:  One for all users and one personal to themselves.  Both will work though.  I would argue that any admin with the sophistication to use Chocolatey to install/upgrade Ventoy can figure out what is going on by checking the versions of the two Ventoys and their locations.  IOW, I wouldn't say that unusual circumstance is a valid reason not to fix the package.

If you want to go through the hassle of building it for all users or just one user, IMHO, all-users should definitely be the default because that is what is expected for Chocolatey packages (and for new users).  In that case, unless users are paying close attention, the minor possible "risk" with the shortcuts remains, so what was the point of the extra work?

I guess what I am saying is that there are edge-cases whether you change the package to install shortcuts for all users or leave it so the shortcuts are for only the installing user, but the expectation of packages to be for all users and the unusual and minor issues around the all-user edge cases leads me to believe it is better to just remove the personal shortcuts for the installing/upgrade user; create shortcuts for all users; and not worry about any other, former, admin, users.

**Comment by asheroto** [comment]
Thanks for the feedback. I have submitted version `1.0.97.20240415`.

https://community.chocolatey.org/packages/ventoy/1.0.97.20240415
