### ISSUE TITLE
[Update Request]: Ventoy 1.0.98

### ISSUE THREAD

**Issue by candrapersada** [asheroto/ChocolateyPackages#11]
### Checklist

- [X] I have verified that there are no pending versions in the `Version History` section of the Chocolatey package ([more info](https://github.com/asheroto/ChocolateyPackages/blob/master/README.md#updates))
- [X] I have specified the name of the package and the current version of the software in the issue's title

### Package Name

ventoy

### Software Name

Ventoy

### Package URL

https://community.chocolatey.org/packages/ventoy

### Current Chocolatey Version

Ventoy 1.0.97.20240415

### Current Software Version

1.0.98

**Comment by asheroto** [comment]
Ventoy is part of my automatic update script, so it'll update automatically twice a week. It just hadn't got to it yet. I ran a manual update and have pushed it to the repo.

https://community.chocolatey.org/packages/ventoy/1.0.98
