### ISSUE TITLE
[Request]: is there ventoy x64 support

### ISSUE THREAD

**Issue by candrapersada** [asheroto/ChocolateyPackages#12]
### Describe the feature or improvement you're requesting

is there any support or how to use ventoy x64?

**Comment by asheroto** [comment]
Hey there,

For the longest time they just had one EXE. I'll have to check the `%AppData%\Ventoy` folder again and adjust the Choco package for desktop shortcuts.

Check that folder and you'll find the EXE if there is more than one.

**Comment by asheroto** [comment]
I'll check tomorrow and update.

**Comment by asheroto** [comment]
Hi there, sorry for the delay. I've been swamped lately.

I just see `Ventoy2Disk.exe` for Ventoy...

https://github.com/ventoy/Ventoy/releases

![image](https://github.com/asheroto/ChocolateyPackages/assets/49938263/14f0da2e-5124-4928-8e30-cb2642a5bda3)

Whereas iVentoy supports both x86 and x64...

https://github.com/ventoy/PXE/releases

(example of 64-bit zip)
![image](https://github.com/asheroto/ChocolateyPackages/assets/49938263/cec694d9-462b-4b49-a1e8-3afeebf419b2)

**Comment by candrapersada** [comment]
but there is Ventoy2Disk_X64.exe in `altexe` folder
![image](https://github.com/asheroto/ChocolateyPackages/assets/36833664/6b590fb2-6837-48a4-8364-30ea7012f5a9)
![image](https://github.com/asheroto/ChocolateyPackages/assets/36833664/078c5c54-b766-435a-b238-171b154230fb)

**Comment by asheroto** [comment]
@candrapersada I have added support for the `altexe` shortcuts in version `1.0.98.20240603`.

https://community.chocolatey.org/packages/ventoy/1.0.98.20240603

You can see details on how to use them in [Package Parameters](https://community.chocolatey.org/packages/ventoy/1.0.98.20240603#package-parameters).

Pending Choco moderator approval.

**Comment by candrapersada** [comment]
if update `ventoy` from 1.0.98 to 1.0.98.20240603
does it automatically update `ventoy` shortcuts to x64 for windows 64, and x86 for windows 32

**Comment by asheroto** [comment]
No, the default EXE is used for all. You can specify an install param to use the 64-bit shortcut instead.

I don't see any real benefit by using the 64-bit version since the files are so tiny I don't think there would be any performance enhancements over the default version.
